[id='proc-run-locally-qs_{context}']

= Run the OptaWeb Vehicle Routing runLocally.sh script in quick start mode

The easiest way to get started with OptaWeb Vehicle Routing is to run the `runLocally.sh` without any arguments.

.Prerequisites
We tell them to down load a JAR earlier and that appears to work so I don't think this is correct:
* `optaweb-vehicle-routing` repository is cloned on your computer.
* The `optaweb-vehicle-routing-distribution-{VRPVERSIONLONG}.Final.zip ` distribution has been extracted on your computer.
* Internet access is available.
* Java 8 or higher is installed.

.Procedure
. Change directory to the `optaweb-vehicle-routing-distribution-{VRPVERSIONLONG}.Final/bin` directory.
. Enter the following command:
+
[source]
----
 ./runLocally.sh
----
 . If prompted to create the `.optaweb-vehicle-routing` directory, enter `y`. You will be prompted to create this directory the first time you run the script.
 . If prompted to download an OSM file, enter `y`. You will be prompted to download an OSM file the first time you run the script.
. Confirm that the OSM file needed to work with the built-in data set was downloaded.
COMMENT: How do I confirm? Or it that what I did when I entered 'y' above? Should we tell them how to choose a different OSM file at this stage?
+
The application starts after the OSM file is downloaded.
Enter the following URL in a web browser to open the OptaWeb Vehicle Routing UI:
+
[source]
----
http://localhost:8080
----
//COMMENT: Add link to using.

NOTE: The first time you run the script, it will take  a few minutes to start because the OSM file must be imported by GraphHopper and stored as a road network graph.
The next time you run the `runlocally.sh` script, load times will be significantly faster.
