[id='proc-run-locally-airdistance_{context}']

= Run the OptaWeb Vehicle Routing runLocally.sh script in air distance mode

OptaWeb Vehicle Routing can work in air distance mode that calculates travel times based on the distance between two coordinates.
Use this mode in situations where you need to get OptaWeb Vehicle Routing up and running as quickly as possible and do not want to use an OSM (OpenStreetMap) file.
Air distance mode is only useful if you need to smoke-test OptaWeb Vehicle Routing and you do not need accurate travel times.

.Procedure
Run the `runLocally.sh` script with `--air` argument to start OptaWeb Vehicle Routing in air distance mode:

[source,bash]
----
./bin/runLocally.sh --air
----

== Tweak the data directory
COMMENT: Where exactly is the data directory?

* To use a different data directory, write its absolute path to the `.DATA_DIR_LAST` file at the project root.

* To change country codes associated with a region, edit the corresponding file under `_DATA_DIR_/country_codes/`.
+
For example, you could have downloaded an OSM file for Scotland, for which the script fails to guess the country code.
In this case, set the content of `_DATA_DIR_/country_codes/scotland-latest` to `GB`.

* To remove a region, delete the corresponding OSM file from `_DATA_DIR_/openstreetmap/` and GraphHopper directory from `_DATA_DIR_/graphhopper/`.
