[id='run-locally-noninteractive-proc_{context}']

= Run the OptaWeb Vehicle Routing runLocally.sh script in non-interactive mode

Use OptaWeb Vehicle Routing in non-interactive mode to start OptaWeb Vehicle Routing with a single command that includes an OSM file that you downloaded previously.
This is useful when you want to switch between regions quickly or when doing a demo.

.Prerequisites
ifdef::PRODUCTIZED[]
* OptaWeb Vehicle Routing has been successfully built with Maven as described in xref:download-ref-imp-proc_{context}[].endif::PRODUCTIZED[]
endif::PRODUCTIZED[]
* The OSM file for the region that you want to use has been downloaded. For information about downloading OSM files, see xref:run-locally-interactive-proc_{context}[].
* Internet access is available.


.Procedure
ifdef::PRODUCTIZED[]
. Change directory to `{URL_COMPONENT_VRP}-distribution-{MAVEN_ARTIFACT_VERSION}/sources`.
endif::PRODUCTIZED[]
ifdef::COMMUNITY[]
. Change to the project root directory.
endif::COMMUNITY[]


. Execute the following command where `<OSM_FILE_NAME>` is an OSM file that you downloaded previously:
+
[source]
----
./runLocally.sh <OSM_FILE_NAME>
----
